### PR TITLE
Fix module load code formatting

### PR DESCRIPTION
**Pull request by doismellburning**

### CODE REVIEW

**Comment by hexameron** [comment]
I can fix that tomorrow when I build new modules. I think that it was pure
luck that it was working at all the last time, it seems more stable now.

**Comment by doismellburning** [comment]
Um, are you talking about a different PR? This is just text formatting.

**Comment by hexameron** [comment]
That looks a lot better, thanks.

**Comment by doismellburning** [comment]
Closing, since fixed in subsequent commit (e20f90d2)

**Pull request closed without merging**
